# Generated by Django 4.0 on 2021-12-14 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=255)),
                ('producers', models.CharField(max_length=100)),
                ('directors', models.CharField(default=None, max_length=100)),
                ('genre', models.CharField(default=None, max_length=20)),
                ('release_date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('poster', models.ImageField(upload_to='photos')),
                ('trailer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moviepages.movie')),
            ],
        ),
    ]
