# Generated by Django 3.2.8 on 2021-11-21 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('actors', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=30)),
                ('release_date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('poster', models.ImageField(upload_to='photos')),
                ('trailer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moviepages.movies')),
            ],
        ),
    ]
