# Generated by Django 3.2.8 on 2021-11-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepages', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
