# Generated by Django 3.2.8 on 2021-12-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviepages', '0003_auto_20211121_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
