# Generated by Django 3.2.8 on 2021-12-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviepages', '0004_rename_movie_id_rating_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='producer',
            new_name='producers',
        ),
    ]
