# Generated by Django 3.2.8 on 2021-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepages', '0005_auto_20211213_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
